
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using ZXing;
using ZXing.Common;
using ZXing.Net.Mobile.Forms;
using ZXing.QrCode;
using System.IO;



namespace App1
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]


    public partial class MainPage : ContentPage
    { 

        public MainPage()
        {
            InitializeComponent();
        }

        //GenerateQRCode() calls a Rest API and returns a QR code generated by the given string
        private void GenerateQRCode (string dataString)
        {
            using (var client = new HttpClient())
            {
                String url = $"https://api.qrserver.com/v1/create-qr-code/?size=500x500&data={dataString}";
                var response = client.GetAsync(url).Result;

                if (response.IsSuccessStatusCode)
                {
                    var responseContent = response.Content;
                    var inputStream = response.Content.ReadAsStreamAsync().Result;
                    QRCodeImg.Source = ImageSource.FromStream(() => inputStream);

                }
            }
        }

        public void ScanQRCode()
        {
            var scanPage = new ZXingScannerPage();
            // Navigate to our scanner page
            Navigation.PushAsync(scanPage);
            scanPage.OnScanResult += (result) =>
            {
                scanPage.IsScanning = false;

                Device.BeginInvokeOnMainThread(async () =>
                {
                    await Navigation.PopAsync();
                    await DisplayAlert("Scanned Barcode", result.Text, "OK");
                });
            };
        }

        public void GenerateQRCodeButton(object sender, System.EventArgs e)
        {
            GenerateQRCode("Chingus' Dingus");
        }
        public void ScanQRCodeButton(object sender, System.EventArgs e)
        {
            ScanQRCode();
        }

        void Button2(object sender, System.EventArgs e)
        {
            DisplayAlert("Title", "Hahahahahahahaha","OK");
        } 

        void AorITest(object sender, System.EventArgs e)
        {

        }

    }
}
